# --- Base image with Node.js and Debian Slim ---
FROM node:18-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install
RUN npm install react-toastify
RUN npm install react-icons
RUN npm install three
RUN npm install vanta
RUN npm install emoji-picker-react

# Copy the rest of the app
COPY . .

# Expose Next.js dev server port
EXPOSE 3000

# Default command for development
CMD ["npm", "run", "dev"]
